[General]
dns-server = 23.95.222.18:8053
dns-direct-system = true
[Rule]
# 广告域名
RULE-SET,https://raw.githubusercontent.com/Loyalsoldier/clash-rules/release/reject.txt,REJECT
# 私有域名
RULE-SET,https://raw.githubusercontent.com/Loyalsoldier/clash-rules/release/private.txt,DIRECT
# 苹果域名
RULE-SET,https://raw.githubusercontent.com/Loyalsoldier/clash-rules/release/apple.txt,DIRECT
RULE-SET,https://raw.githubusercontent.com/Loyalsoldier/clash-rules/release/icloud.txt,DIRECT
# 黑名单域名
RULE-SET,https://raw.githubusercontent.com/Loyalsoldier/clash-rules/release/gfw.txt,PROXY
# 直连域名
RULE-SET,https://raw.githubusercontent.com/Loyalsoldier/clash-rules/release/direct.txt,DIRECT
# 代理域名
RULE-SET,https://raw.githubusercontent.com/Loyalsoldier/clash-rules/release/proxy.txt,PROXY
# 私有IP
RULE-SET,https://raw.githubusercontent.com/Loyalsoldier/clash-rules/release/lancidr.txt,DIRECT
# 中国IP
RULE-SET,https://raw.githubusercontent.com/Loyalsoldier/clash-rules/release/cncidr.txt,DIRECT
GEOIP,CN,DIRECT
# 最终代理
FINAL,PROXY