#!/usr/sbin/nft -f
flush ruleset

define INGRESS_INTERFACE = "eth0"
define PORT_RANGE = 10000-29999
define HYSTERIA_SERVER_PORT = 8888

table ip hysteria_porthopping {
    chain prerouting {
        type nat hook prerouting priority dstnat; policy accept;
        iifname $INGRESS_INTERFACE udp dport $PORT_RANGE counter redirect to :$HYSTERIA_SERVER_PORT
    }
}